### ISSUE TITLE
Use `U` type for string fields

### ISSUE THREAD

**Issue by esheldon** [des-labs/easyaccess#5]
It appears that `S`  is being used for string fields, but for new fitsio/python 3 we should use `U`

This is better for the fits output, but is actually required for sensible text output.  For example one would see this in a text output file currently.  Notice the bytes start which would not be parseable for a normal text file reader

```
FILENAME
b'DES0000+0209_r5064p01_z_meds-Y6A1_MEDS.fits'
b'DES0000+0209_r5064p01_z_meds-Y6A1_MEDS.fits'
b'DES0000-0207_r5064p01_z_meds-Y6A1_MEDS.fits'
b'DES0000-0207_r5064p01_z_meds-Y6A1_MEDS.fits'
```

**Comment by manning-ncsa** [comment]
Thanks for bringing this to our attention. I am not personally familiar with most of the easyaccess code. Can you provide a specific example in the code where this applies?

**Comment by manning-ncsa** [comment]
Thank you for opening https://github.com/des-labs/easyaccess/pull/6 to address this issue.
